# article.params.x=01
# article.params.y=02
# global.params.p2=99
# server:
#   port: 8082

spring:
  application:
    name: donArticle
  jpa:
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/donProject-realm
          jwk-set-uri: http://localhost:8080/realms/donProject-realm/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
  datasource:
    url: jdbc:mysql://localhost:3306/donArticle
    username: donArticle
    password: donArticle
  