





spring:
  application:
    name: donArticle
  jpa:
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
  datasource:
    url: jdbc:mysql://${DBDONARTICLE://localhost:3306/donarticle}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER-URI:http://localhost:8080/realms/donProject-realm}
          jwk-set-uri: ${JWT-SER-URI:http://localhost:8080/realms/donProject-realm/protocol/openid-connect/certs}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}    