
spring:
  application:
    name: donDemande
  jpa:
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/donDemande
    username: donDemande
    password: donDemande
 
feign:
  hystrix:
    enabled: false      