
spring:
  application:
    name: gateWay
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://donArticle
          predicates:
            - Path=/articles/**
        - id: r2
          uri: lb://donDemande
          predicates:
            - Path=/demandes/**            
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG


